## 08 ``Numpy`` 中的聚合操作

### sum

In [1]:
import numpy as np

L = np.random.random(100)
sum(L)

55.38098279959315

In [2]:
np.sum(L)

55.38098279959317

In [3]:
np.random.rand(10)

array([0.83824478, 0.10489137, 0.33883297, 0.76013676, 0.24054704,
       0.94542681, 0.04659836, 0.54120509, 0.54849464, 0.64921862])

In [4]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

71.9 ms ± 480 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
756 µs ± 17 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### min, max

In [6]:
np.min(big_array)

1.1582419187083914e-06

In [7]:
np.max(big_array)

0.9999987853393867

In [8]:
big_array.min()

1.1582419187083914e-06

In [9]:
big_array.max()

0.9999987853393867

In [10]:
big_array.sum()

500187.97144699376

### 多维度聚合

In [11]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)

120

In [13]:
np.sum(X, axis=0) # axis=0 按列，把第0个维度不要了

array([24, 28, 32, 36])

沿着第一个维度，行的方向进行计算，得到的是每一列相加的值。

In [15]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

注意：axis描述的是将要被压缩的维度。

### 其他聚合操作

In [16]:
np.prod(X)

0

得到所有元素的乘积

In [17]:
np.prod(X + 1)

2004189184

In [18]:
np.mean(X)

7.5

In [19]:
np.median(X)

7.5

中位数

In [20]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [21]:
np.median(v)

2.0

In [22]:
np.percentile(big_array, q=50)

0.5000789853358597

统计学中的50%，百分位

In [23]:
np.median(big_array)

0.5000789853358597

In [24]:
np.percentile(big_array, q=100)

0.9999987853393867

In [25]:
np.max(big_array)

0.9999987853393867

In [26]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

1.1582419187083914e-06
0.2504851383627331
0.5000789853358597
0.7497502524386181
0.9999987853393867


In [27]:
np.var(big_array)

0.0832897992641161

var 求方差

In [28]:
np.std(big_array)

0.28859972152466834

std 求标准差

In [29]:
x = np.random.normal(0, 1, 1000000)

均值为0，标准差为1

In [30]:
np.mean(x)

-0.0004044717167191069

In [31]:
np.std(x)

1.0008493498832256