## 09 ``Numpy`` 中arg运算

In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, 1000000)

### 索引

In [3]:
np.min(x)

-4.6379497523299875

In [4]:
np.argmin(x) # 最小值位置在哪

646024

这个最小值的索引是多少

In [5]:
x[490149]

-0.1804738101122614

In [6]:
np.min(x)

-4.6379497523299875

In [7]:
np.argmax(x)

852352

In [8]:
x[45071]

0.3009770181393359

In [9]:
np.max(x)

4.691886246616233

### 排序和使用索引

In [10]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
np.random.shuffle(x)
x

array([ 8,  4,  2,  5,  6, 11,  7,  3, 14, 15,  9, 13, 10,  1, 12,  0])

对向量进行乱序操作，shuffle是洗牌操作

In [12]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

np.sort 不会改变x，返回被改变的数组。x.sort会对x进行修改

In [13]:
x

array([ 8,  4,  2,  5,  6, 11,  7,  3, 14, 15,  9, 13, 10,  1, 12,  0])

In [14]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
X = np.random.randint(10, size=(4,4))
X

array([[3, 6, 4, 6],
       [7, 7, 2, 9],
       [9, 7, 7, 4],
       [7, 6, 3, 8]])

In [19]:
np.sort(X)

array([[3, 4, 6, 6],
       [2, 7, 7, 9],
       [4, 7, 7, 9],
       [3, 6, 7, 8]])

默认是把每一行变为有序

In [20]:
np.sort(X, axis=0)

array([[3, 6, 2, 4],
       [7, 6, 3, 6],
       [7, 7, 4, 8],
       [9, 7, 7, 9]])

In [21]:
np.sort(X, axis=1)

array([[3, 4, 6, 6],
       [2, 7, 7, 9],
       [4, 7, 7, 9],
       [3, 6, 7, 8]])

#### 使用索引

In [22]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
np.random.shuffle(x)

In [27]:
x

array([15,  0,  8,  7, 12,  1, 14,  5, 11,  6,  2,  9,  3, 10, 13,  4])

In [28]:
np.argsort(x)

array([ 1,  5, 10, 12, 15,  7,  9,  3,  2, 11, 13,  8,  4, 14,  6,  0],
      dtype=int64)

最小的数字在数组中索引为5的位置，以此类推

In [29]:
np.partition(x, 3)

array([ 0,  1,  2,  3,  4,  5, 14, 12, 11,  6,  7,  9,  8, 10, 13, 15])

标定点，3前面的数字都比3小，4后面的数字都比3大,但不是有序

In [30]:
np.argpartition(x, 3)

array([ 1,  5, 10, 12, 15,  7,  6,  4,  8,  9,  3, 11,  2, 13, 14,  0],
      dtype=int64)

In [31]:
X

array([[3, 6, 4, 6],
       [7, 7, 2, 9],
       [9, 7, 7, 4],
       [7, 6, 3, 8]])

In [32]:
np.argsort(X, axis=1)

array([[0, 2, 1, 3],
       [2, 0, 1, 3],
       [3, 1, 2, 0],
       [2, 1, 0, 3]], dtype=int64)

In [33]:
np.argpartition(X, 2, axis=1)

array([[0, 2, 1, 3],
       [2, 1, 0, 3],
       [3, 1, 2, 0],
       [2, 1, 0, 3]], dtype=int64)