## 03 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets 

In [2]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
X = iris.data

In [4]:
y = iris.target

In [5]:
X.shape

(150, 4)

In [6]:
y.shape

(150,)

### train_test_split

分离出一部分数据做训练，另外一部分数据做测试。

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
shuffled_indexes = np.random.permutation(len(X))
shuffled_indexes

array([ 44,  30, 119,  23,  77, 101,  55,  18, 130,  78,  58, 128, 141,
         4, 122,  62,  48, 111,  94,  88, 140,  61,  13, 112,  33, 108,
         8, 129,  69, 100,  56,  20,   6,  66,  22,  11, 105, 123,  67,
        64, 134,  75,   0,  82, 124, 113,  28, 144,  92,  57,  41, 107,
         1,  26,  70,  89,  47, 148,  43,  91,  16,  79, 117, 116,  97,
        15,  84, 137, 114,   5,  40, 102,  99,  71,  36,  60, 109,  76,
        93,  98,  59,   3, 146, 131, 136,  12,  51,  27, 145,  63, 115,
        29,  25, 118,   7, 135,  34,  80,  68, 110, 139,   9,  53,  73,
        65, 121,  19,  74,  49,  86, 138,  95, 132, 127, 142,  32,  38,
       143, 104, 103,  31, 120, 106,  37,  45,  83,  54,  10, 126,  72,
        46,  14,  21,  96,  42, 147,  50,  85,  90, 133, 149, 125,  81,
         2,  52,  87,  17,  35,  24,  39])

In [9]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [10]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]

In [11]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [12]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [13]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 封装

In [14]:
from playML.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [15]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [16]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 测试我们的算法

In [17]:
from playML.kNN import KNNClassifier

my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [18]:
y_predict

array([2, 0, 1, 2, 2, 1, 2, 2, 0, 0, 0, 1, 0, 1, 1, 2, 2, 2, 2, 1, 2, 1,
       1, 2, 0, 1, 1, 1, 1, 1])

In [19]:
y_test

array([1, 0, 1, 2, 2, 1, 2, 2, 0, 0, 0, 1, 0, 1, 1, 2, 2, 2, 2, 1, 2, 1,
       1, 2, 0, 1, 2, 1, 1, 1])

In [20]:
sum(y_predict == y_test)

28

In [21]:
sum(y_predict == y_test) / len(y_test)

0.9333333333333333

#### sklearn中的train_test_split

In [22]:
from sklearn.model_selection import train_test_split

train_test_split

<function sklearn.model_selection._split.train_test_split(*arrays, test_size=None, train_size=None, random_state=None, shuffle=True, stratify=None)>

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=613)

In [25]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


In [26]:
from sklearn.neighbors import KNeighborsClassifier

In [27]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=6)

In [28]:
y_predict = kNN_classifier.predict(X_test)
y_predict

array([2, 2, 0, 2, 1, 1, 1, 0, 1, 0, 1, 1, 2, 1, 1, 0, 0, 2, 2, 1, 0, 1,
       1, 2, 1, 2, 2, 1, 2, 2])

In [29]:
y_test

array([2, 2, 0, 2, 1, 1, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 0, 2, 2, 1, 0, 1,
       1, 1, 1, 2, 2, 1, 2, 2])

In [30]:
sum(y_predict == y_test)

28

In [31]:
sum(y_predict == y_test) / len(y_test)

0.9333333333333333